const alumnosFicticios = [
        {
            CorreoElectronico: "valentina.gomez25@example.com",
            Contrasea: "U2FsdGVkX19PLRHBrBI7ke4en3gfUfh3L0GaubLP6M4=",
            Telefono: "1134567890",
            AoIngreso: 2023,
            Materia: "Bases de Datos",
            EstadoEnLaMateriaa: "Cursando normalmente",
            Comentario: "Me gusta la materia",
            ClasesAFavor: 0,
            FechaDePago: null,
            DineroQueDebe: 0,
            Pack: 0,
            nombre: "Valentina",
            apellido: "Gómez"
        },
        {
            CorreoElectronico: "juan.perez34@example.com",
            Contrasea: "U2FsdGVkX1A9XkMHvCR8fYpj2nWcZRvEwOqGkLp5gJk=",
            Telefono: "1145678901",
            AoIngreso: 2022,
            Materia: "Matemáticas",
            EstadoEnLaMateriaa: "Aprobada",
            Comentario: "Muy buen desempeño",
            ClasesAFavor: 2,
            FechaDePago: "2024-04-10",
            DineroQueDebe: 0,
            Pack: 1,
            nombre: "Juan",
            apellido: "Pérez"
        },
        {
            CorreoElectronico: "sofia.lopez99@example.com",
            Contrasea: "U2FsdGVkX1+fsT1x5GbC37Jx9Ev3UXNf4qKmXjEpN0Y=",
            Telefono: "1156789012",
            AoIngreso: 2021,
            Materia: "Programación",
            EstadoEnLaMateriaa: "Pendiente",
            Comentario: "Debe mejorar en lógica",
            ClasesAFavor: 1,
            FechaDePago: null,
            DineroQueDebe: 500,
            Pack: 0,
            nombre: "Sofía",
            apellido: "López"
        },
        {
            CorreoElectronico: "martin.fernandez88@example.com",
            Contrasea: "U2FsdGVkX1+e3n8k9Jv4k8h2l3m4n5o6p7q8r9s0t1u2=",
            Telefono: "1167890123",
            AoIngreso: 2020,
            Materia: "Física",
            EstadoEnLaMateriaa: "Recursando",
            Comentario: "Necesita apoyo en teoría",
            ClasesAFavor: 0,
            FechaDePago: null,
            DineroQueDebe: 1000,
            Pack: 0,
            nombre: "Martín",
            apellido: "Fernández"
        },
        {
            CorreoElectronico: "camila.sanchez77@example.com",
            Contrasea: "U2FsdGVkX1+z8y7x6w5v4u3t2s1r0q9p8o7n6m5l4k3=",
            Telefono: "1178901234",
            AoIngreso: 2023,
            Materia: "Química",
            EstadoEnLaMateriaa: "Cursando normalmente",
            Comentario: "Participa activamente",
            ClasesAFavor: 1,
            FechaDePago: "2024-05-01",
            DineroQueDebe: 0,
            Pack: 1,
            nombre: "Camila",
            apellido: "Sánchez"
        },
        {
            CorreoElectronico: "lucas.martinez66@example.com",
            Contrasea: "U2FsdGVkX1+q1w2e3r4t5y6u7i8o9p0a1s2d3f4g5h6=",
            Telefono: "1189012345",
            AoIngreso: 2021,
            Materia: "Inglés Técnico",
            EstadoEnLaMateriaa: "Aprobada",
            Comentario: "Excelente nivel",
            ClasesAFavor: 0,
            FechaDePago: "2024-03-15",
            DineroQueDebe: 0,
            Pack: 0,
            nombre: "Lucas",
            apellido: "Martínez"
        },
        {
            CorreoElectronico: "florencia.ruiz55@example.com",
            Contrasea: "U2FsdGVkX1+z9x8c7v6b5n4m3l2k1j0h9g8f7d6s5a4=",
            Telefono: "1190123456",
            AoIngreso: 2022,
            Materia: "Análisis Matemático",
            EstadoEnLaMateriaa: "Pendiente",
            Comentario: "Falta entregar trabajos",
            ClasesAFavor: 2,
            FechaDePago: null,
            DineroQueDebe: 1500,
            Pack: 0,
            nombre: "Florencia",
            apellido: "Ruiz"
        },
        {
            CorreoElectronico: "diego.garcia44@example.com",
            Contrasea: "U2FsdGVkX1+e4r5t6y7u8i9o0p1a2s3d4f5g6h7j8k9=",
            Telefono: "1101234567",
            AoIngreso: 2020,
            Materia: "Sistemas Digitales",
            EstadoEnLaMateriaa: "Cursando normalmente",
            Comentario: "Buen desempeño en prácticas",
            ClasesAFavor: 1,
            FechaDePago: "2024-04-20",
            DineroQueDebe: 0,
            Pack: 1,
            nombre: "Diego",
            apellido: "García"
        },
        {
            CorreoElectronico: "mariana.torres22@example.com",
            Contrasea: "U2FsdGVkX1+z1x2c3v4b5n6m7l8k9j0h1g2f3d4s5a6=",
            Telefono: "1123456789",
            AoIngreso: 2023,
            Materia: "Estadística",
            EstadoEnLaMateriaa: "Cursando normalmente",
            Comentario: "Le interesa la materia",
            ClasesAFavor: 0,
            FechaDePago: null,
            DineroQueDebe: 0,
            Pack: 0,
            nombre: "Mariana",
            apellido: "Torres"
        },
        {
            CorreoElectronico: "agustin.mendez11@example.com",
            Contrasea: "U2FsdGVkX1+q2w3e4r5t6y7u8i9o0p1a2s3d4f5g6h7=",
            Telefono: "1134567801",
            AoIngreso: 2022,
            Materia: "Álgebra",
            EstadoEnLaMateriaa: "Aprobada",
            Comentario: "Participativo en clase",
            ClasesAFavor: 1,
            FechaDePago: "2024-05-05",
            DineroQueDebe: 0,
            Pack: 1,
            nombre: "Agustín",
            apellido: "Méndez"
        },
        {
            CorreoElectronico: "carla.vazquez33@example.com",
            Contrasea: "U2FsdGVkX1+e5r6t7y8u9i0o1p2a3s4d5f6g7h8j9k0=",
            Telefono: "1145678012",
            AoIngreso: 2021,
            Materia: "Electrónica",
            EstadoEnLaMateriaa: "Pendiente",
            Comentario: "Debe mejorar en prácticas",
            ClasesAFavor: 0,
            FechaDePago: null,
            DineroQueDebe: 800,
            Pack: 0,
            nombre: "Carla",
            apellido: "Vázquez"
        },
        {
            CorreoElectronico: "franco.silva77@example.com",
            Contrasea: "U2FsdGVkX1+z3x4c5v6b7n8m9l0k1j2h3g4f5d6s7a8=",
            Telefono: "1156780123",
            AoIngreso: 2020,
            Materia: "Termodinámica",
            EstadoEnLaMateriaa: "Recursando",
            Comentario: "Necesita apoyo extra",
            ClasesAFavor: 2,
            FechaDePago: null,
            DineroQueDebe: 1200,
            Pack: 0,
            nombre: "Franco",
            apellido: "Silva"
        },
        {
            CorreoElectronico: "julieta.rios88@example.com",
            Contrasea: "U2FsdGVkX1+q4w5e6r7t8y9u0i1o2p3a4s5d6f7g8h9=",
            Telefono: "1167801234",
            AoIngreso: 2023,
            Materia: "Redes",
            EstadoEnLaMateriaa: "Cursando normalmente",
            Comentario: "Muy activa en clase",
            ClasesAFavor: 1,
            FechaDePago: "2024-05-10",
            DineroQueDebe: 0,
            Pack: 1,
            nombre: "Julieta",
            apellido: "Ríos"
        },
  // Puedes seguir agregando más si quieres
    ];